version: '3'
services:
  api:
    build:
      context: api/
      dockerfile: Dockerfile
    ports:
      - 3000:80
  front:
    build:
      context: front/
      dockerfile: Dockerfile
    ports:
      - 80:4200
      